// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvuxgccegfyyjqipjakw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2dXhnY2NlZ2Z5eWpxaXBqYWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzg1NzIsImV4cCI6MjA2OTkxNDU3Mn0.HaBB4f8HwRY7UOLXpM_OaLgjBteZ24EUqmgmAosmZ8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});